webdriver:
  timeout: 5
  browser_type: "Chrome"

logging:
  level: "info"
  formatter: "%(asctime)s - %(lineno)d - %(funcName)s - %(levelname)s - %(message)s"

test_case_path:
  path: ""

DB_config:
  mysql:
    url: ""
    port: ""
    database: ""
    username: ""
    password: ""

  redis:
    url: ""
    port: ""
    password: ""

  mongDB:
    url: ""
    port: ""



