webdriver:
  timeout: 5
  browser_type: "Chrome"
  pytest:
    - "-n=4"
    - "-s"

allure:
  result_path: ""
  report_path: ""
  environment:
    Browser: "Chrome"
    Browser_Version: "63.0"
    Stand: "Production"
    ApiUrl: "127.0.0.1/login"
    python_Version: "3.7"
  categories:
    [
      {
        "name": "Ignored tests",
        "matchedStatuses": ["skipped"]
      },
      {
        "name": "Infrastructure problems",
        "matchedStatuses": ["broken", "failed"],
        "messageRegex": ".*bye-bye.*"
      },
      {
        "name": "Outdated tests",
        "matchedStatuses": ["broken"],
        "traceRegex": ".*FileNotFoundException.*"
      },
      {
        "name": "Product defects",
        "matchedStatuses": ["failed"]
      },
      {
        "name": "Test defects",
        "matchedStatuses": ["broken"]
      }
    ]


logging:
  level: "info"
  formatter: "%(asctime)s - %(lineno)d - %(funcName)s - %(levelname)s - %(message)s"

test_case_path:
  path: ""



DB_config:
  mysql:
    host: "192.168.151.193"
    port: "3307"
    db: "test"
    user: "root"
    password: "c6l7r8ceacvi2010vs"
    charset: "utf8"

  redis:
    url: ""
    port: ""
    password: ""

  mongo:
    url: ""
    db: ""



